-- AlterEnum
-- This migration adds DONOR_REQUEST_UPDATED to the BusinessEventType enum
ALTER TABLE `business_events` 
  MODIFY COLUMN `type` ENUM('DONOR_REQUEST_CREATED', 'DONOR_REQUEST_REVIEWED', 'DONOR_REQUEST_UPDATED', 'REQUEST_DIRECTED_TO_POINT', 'PICKUP_APPROVED', 'DRIVER_ASSIGNED_TO_ROUTE', 'ROUTE_STARTED', 'DRIVER_ARRIVED_AT_DONOR', 'MATERIAL_COLLECTED', 'DRIVER_ARRIVED_AT_COLLECTION_POINT', 'MATERIAL_DELIVERED_TO_COLLECTION_POINT', 'WEIGHT_REGISTERED', 'DECLARATION_GENERATED', 'ROUTE_FINISHED', 'REQUEST_CANCELLED') NOT NULL;
